INSERT INTO Silver.erp_cust_az12
   (CID,
	BDATE,
	GEN
)
SELECT 
	CASE WHEN CID LIKE 'NAS%' THEN SUBSTRING(TRIM(CID),4,LEN(CID))
		 ELSE CID
	END AS CID,
	CASE WHEN BDATE > GETDATE() THEN NULL
		ELSE BDATE
	END AS BDATE,
	CASE 
		WHEN GEN IS NULL THEN 'n/a'
		WHEN UPPER(TRIM(GEN)) IN ('F','FEMALE') THEN 'Female'
		WHEN UPPER(TRIM(GEN))IN ('M','MALE')THEN 'Male'
		WHEN UPPER(TRIM(GEN))='' THEN 'n/a'
		ELSE TRIM(GEN)
	END AS GEN
FROM Bronze.erp_cust_az12
